#!/bin/bash
# PreToolUse hook: generated files are regenerated by their tool, never
# hand-edited. Refuses Edit/Write/MultiEdit/NotebookEdit on any guarded path
# (exit 2, reason on stderr). For Bash, asks before a command that pairs a
# guarded path with an in-place write; the regeneration tools themselves
# (publish.py, build_hf_lows.py, the cp/rm in the flat recipe) are ordinary
# Bash commands and pass through untouched.
#
# Paths are repo-relative. A trailing slash guards the whole directory.
GUARDED=(
  "flat/"
  "docs/data/"
  "web/TCWind_JTWC/BestTrackData.gs"
  "tests/tcwind_jtwc/data/gtcm_findings.json"
)
REGEN_HINT="See the 'Generated files' table in CLAUDE.md for the regeneration command."

set -u
input=$(cat)
tool=$(printf '%s' "$input" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("tool_name",""))' 2>/dev/null || true)
root="${CLAUDE_PROJECT_DIR:-$(pwd)}"

matches_guarded() {  # $1 = repo-relative path
  local p="$1" g
  for g in "${GUARDED[@]}"; do
    case "$g" in
      */) [[ "$p" == "$g"* ]] && return 0 ;;
      *)  [[ "$p" == "$g" ]] && return 0 ;;
    esac
  done
  return 1
}

case "$tool" in
  Edit|Write|MultiEdit|NotebookEdit)
    fp=$(printf '%s' "$input" | python3 -c 'import json,sys; t=json.load(sys.stdin).get("tool_input",{}); print(t.get("file_path") or t.get("notebook_path") or "")' 2>/dev/null || true)
    [ -z "$fp" ] && exit 0
    rel="${fp#"$root"/}"
    if matches_guarded "$rel"; then
      echo "Refused: $rel is generated. Do not hand-edit it. $REGEN_HINT" >&2
      exit 2
    fi
    ;;
  Bash)
    cmd=$(printf '%s' "$input" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("tool_input",{}).get("command",""))' 2>/dev/null || true)
    [ -z "$cmd" ] && exit 0
    # Ignore stderr/null redirects (2>/dev/null, 2>&1, &>/dev/null) - not writes.
    cleaned=$(printf '%s' "$cmd" | sed -E 's/[0-9&]*>>?[ ]*\/dev\/null//g; s/[0-9]>&[0-9]//g')
    if printf '%s' "$cleaned" | grep -qE '(sed +-i|(^|[^>])>>?[ ]*[^&]|\btee\b|perl +-p?i)'; then
      for g in "${GUARDED[@]}"; do
        if printf '%s' "$cmd" | grep -qF -- "$g"; then
          printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":"This command writes into %s, which is generated. %s Continue only if this IS the regeneration step."}}\n' "$g" "$REGEN_HINT"
          exit 0
        fi
      done
    fi
    ;;
esac
exit 0
