#!/usr/bin/env python3
"""Build the best-track archive the TCWind_JTWC web app serves.

Three basins, one archive:

    WP   JTWC best track,        2005-2024   (from the existing 100-storm
                                              sample; the WP CSV is not
                                              available here - see below)
    NA   NHC HURDAT2 Atlantic,   2004-2024
    EP   NHC HURDAT2 E. Pacific, 2004-2024

Emits, per the build contract:

  data/archive_index.json   light per-storm metadata; this is what the
                            archive browser loads first, so it is kept
                            small (target < 300 KB) and carries no track
                            points at all.
  data/archive_storms.json  {sid: [record, ...]} where record is exactly
                            what besttrack_common.build_storm_records()
                            produces - iso, epoch, lat, lon, vmax, rmw,
                            roci, pres, radii, nature, dist2land,
                            motionDir, motionSpd.
  web/TCWind_JTWC/BestTrackData.gs
                            both of the above, plus gtcm_findings.json if
                            it exists yet, as Apps Script globals
                            ARCHIVE_INDEX / ARCHIVE_STORMS / GTCM_FINDINGS.
                            Generated - never hand-edit.

gtcm_findings.json is produced by verify_gtcm.py, not by this script. This
script only *bundles* it: if tests/tcwind_jtwc/data/gtcm_findings.json
exists it is embedded verbatim as GTCM_FINDINGS, otherwise GTCM_FINDINGS is
emitted as null and a loud warning is printed. So the order of operations
is: run verify_gtcm.py first, then this, and Code.gs's getFindings() has
something to return.

WestPac is read-only input. The IBTrACS WP CSV is not present in this
environment, so data/besttrack_sample.json (100 storms, 2690 records,
seasons 2005-2024, generated by the previous revision of this script) is
consumed as-is and cannot be regenerated. Everything WestPac in the output
is a repackaging of that file, not a re-derivation.

Usage:
    # CSVs found via $IBTRACS_DIR/ibtracs.<BASIN>.csv, or $IBTRACS_NA etc.
    IBTRACS_DIR=/path/to/csvs python3 prep_besttrack_data.py
    # or explicitly
    python3 prep_besttrack_data.py --na ibtracs.NA.csv --ep ibtracs.EP.csv

Nothing here downloads anything: a missing CSV is an error naming the path
and the NCEI URL, not a 50 MB surprise fetch.
"""
import argparse
import json
import os
import random
import sys
from collections import OrderedDict, defaultdict

from besttrack_common import (
    BASIN_AGENCY, BASIN_MIN_SEASON, MAX_SEASON,
    build_storm_records, cache_path, iter_basin_storms,
)

# --------------------------------------------------------------------------
# Tunables
# --------------------------------------------------------------------------
SEED = 20260902           # fixed: the sample must be reproducible
N_NHC_STORMS = 120        # contract cap on NA+EP combined
MIN_RECORDS = 6           # a track shorter than this is not worth browsing
NHC_BASINS = ("NA", "EP")

# Peak-intensity strata. Sampling is spread across these deliberately: an
# unstratified draw is dominated by weak short-lived systems, and a
# "pick the interesting ones" draw is dominated by the famous major
# hurricanes. Neither is what the archive is for.
TIERS = ("TS", "H12", "H35")
TIER_LABEL = {"TS": "TD/TS  (<64 kt)",
              "H12": "Cat 1-2 (64-95 kt)",
              "H35": "Cat 3-5 (>=96 kt)"}

# Soft limits, checked and reported rather than silently enforced.
INDEX_SOFT_LIMIT = 300 * 1024          # contract: archive_index.json < ~300 KB
GS_SOFT_LIMIT = 5 * 1024 * 1024        # contract: BestTrackData.gs < ~5 MB

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
WP_SAMPLE = os.path.join(DATA_DIR, "besttrack_sample.json")
FINDINGS_JSON = os.path.join(DATA_DIR, "gtcm_findings.json")
INDEX_JSON = os.path.join(DATA_DIR, "archive_index.json")
STORMS_JSON = os.path.join(DATA_DIR, "archive_storms.json")
GS_OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "web", "TCWind_JTWC", "BestTrackData.gs"))


def tier_of(peak_vmax):
    if peak_vmax < 64.0:
        return "TS"
    if peak_vmax < 96.0:
        return "H12"
    return "H35"


# --------------------------------------------------------------------------
# Index entries
# --------------------------------------------------------------------------
def index_entry(sid, basin, agency, name, season, recs):
    """The light metadata row for one storm. No track points: the archive
    browser fetches those one storm at a time via getArchiveStorm().

    Longitude convention follows the source: WestPac records are 0-360E,
    NHC records are -180..180. minLon/maxLon are the plain min/max of the
    track EXCEPT for a dateline crosser, where the naive min/max would
    describe a box spanning the entire globe. For those the negative
    longitudes are unwrapped by +360 so the box stays contiguous, which
    means maxLon can exceed 180 (Leaflet accepts that; a consumer that
    does not must wrap it back itself). The record longitudes themselves
    are never altered."""
    lats = [r["lat"] for r in recs]
    lons = [r["lon"] for r in recs]
    if max(lons) - min(lons) > 180.0:
        lons = [x + 360.0 if x < 0 else x for x in lons]
    return OrderedDict([
        ("sid", sid),
        ("basin", basin),
        ("agency", agency),
        ("name", (name or "").strip() or "UNNAMED"),
        ("season", int(season)),
        ("n", len(recs)),
        ("peakVmax", round(max(r["vmax"] for r in recs), 1)),
        ("minLat", round(min(lats), 2)),
        ("maxLat", round(max(lats), 2)),
        ("minLon", round(min(lons), 2)),
        ("maxLon", round(max(lons), 2)),
        ("startIso", recs[0]["iso"]),
        ("endIso", recs[-1]["iso"]),
        ("radiiRecords", sum(1 for r in recs if r["radii"])),
    ])


# --------------------------------------------------------------------------
# WestPac: read-only, already generated
# --------------------------------------------------------------------------
def load_westpac(path):
    """data/besttrack_sample.json -> [(entry, records), ...].

    Not regenerated. The WP IBTrACS CSV is not available in this
    environment, and the contract treats this file as fixed input."""
    if not os.path.exists(path):
        raise IOError(
            "WestPac sample not found: %s\n"
            "  This file cannot be regenerated without the IBTrACS WP CSV, "
            "which is not available here." % path)
    with open(path) as f:
        sample = json.load(f)
    out = []
    for s in sample:
        recs = s["records"]
        if not recs:
            continue
        out.append((index_entry(s["sid"], "WP", BASIN_AGENCY["WP"],
                                s["name"], s["season"], recs), recs))
    return out


# --------------------------------------------------------------------------
# NHC: load, filter, stratified sample
# --------------------------------------------------------------------------
def load_nhc_candidates(paths, log):
    """[(entry, records)] for every eligible NA/EP storm, plus a drop log.

    Eligibility, in order (each rejection counted, none silent):
      - at least MIN_RECORDS usable track points
      - peak Vmax >= 34 kt   (buildFor() in TCWind_JTWC.py refuses to build
        a vortex below tropical-storm strength, so a storm that never got
        there has nothing for the tool to render)
      - at least one record with a reported wind-radii set (a track with no
        radii anywhere cannot exercise the vortex fit at all)
    """
    cands = []
    for basin in NHC_BASINS:
        path = paths[basin]
        drops = defaultdict(int)
        n_seen = 0
        for sid, name, season, rows in iter_basin_storms(basin, path=path):
            n_seen += 1
            recs = build_storm_records(rows)
            if len(recs) < MIN_RECORDS:
                drops["track shorter than %d points" % MIN_RECORDS] += 1
                continue
            peak = max(r["vmax"] for r in recs)
            if peak < 34.0:
                drops["never reached 34 kt"] += 1
                continue
            if not any(r["radii"] for r in recs):
                drops["no wind radii reported anywhere on the track"] += 1
                continue
            cands.append((index_entry(sid, basin, BASIN_AGENCY[basin],
                                      name, season, recs), recs))
        kept = sum(1 for e, _ in cands if e["basin"] == basin)
        log("%s: %d storms in %d-%d, %d eligible, %d dropped"
            % (basin, n_seen, BASIN_MIN_SEASON[basin], MAX_SEASON,
               kept, n_seen - kept))
        for reason, k in sorted(drops.items(), key=lambda kv: -kv[1]):
            log("    dropped %4d  %s" % (k, reason))
    return cands


def stratified_sample(cands, n_target, seed, log):
    """Pick at most n_target storms, reproducibly, spread over
    (basin x season x peak-intensity tier).

    Two passes:
      1. coverage - one storm from every (basin, season) cell that has any
         candidate at all, so no season 2004-2024 is missing from either
         basin. Within the cell the tier that is globally least-represented
         so far wins, so the guaranteed picks do not all land on weak
         systems (which outnumber the rest).
      2. balance - fill the remaining slots by repeatedly taking from the
         least-represented tier, and within that tier from the
         least-represented (basin, season). Ties break on a fixed order, so
         the result depends only on the seed.

    The per-cell candidate lists are shuffled once with random.Random(seed);
    everything after that is deterministic.
    """
    rnd = random.Random(seed)
    cells = defaultdict(list)
    for entry, recs in cands:
        cells[(entry["basin"], entry["season"], tier_of(entry["peakVmax"]))
              ].append((entry, recs))
    for key in cells:
        # sort first so the shuffle input order does not depend on file order
        cells[key].sort(key=lambda er: er[0]["sid"])
        rnd.shuffle(cells[key])

    seasons = list(range(min(BASIN_MIN_SEASON[b] for b in NHC_BASINS),
                         MAX_SEASON + 1))
    picked = []
    tier_count = dict((t, 0) for t in TIERS)
    bs_count = defaultdict(int)

    def take(basin, season, tier):
        bucket = cells.get((basin, season, tier))
        if not bucket:
            return False
        entry, recs = bucket.pop()
        picked.append((entry, recs))
        tier_count[tier] += 1
        bs_count[(basin, season)] += 1
        return True

    # pass 1: every (basin, season) that has candidates gets one
    empty_cells = []
    for basin in NHC_BASINS:
        for season in seasons:
            if season < BASIN_MIN_SEASON[basin]:
                continue
            order = sorted(TIERS, key=lambda t: (tier_count[t], TIERS.index(t)))
            if not any(take(basin, season, t) for t in order):
                empty_cells.append((basin, season))
    for basin, season in empty_cells:
        log("    NOTE %s %d has no eligible storm - season not represented"
            % (basin, season))

    # pass 2: balance
    while len(picked) < n_target:
        progressed = False
        for tier in sorted(TIERS, key=lambda t: (tier_count[t], TIERS.index(t))):
            keys = [(b, s) for b in NHC_BASINS for s in seasons
                    if cells.get((b, s, tier))]
            if not keys:
                continue
            keys.sort(key=lambda k: (bs_count[k], NHC_BASINS.index(k[0]), k[1]))
            take(keys[0][0], keys[0][1], tier)
            progressed = True
            break
        if not progressed:
            break

    picked.sort(key=lambda er: (er[0]["basin"], er[0]["season"], er[0]["sid"]))

    # -- the drop log the contract asks for: what the cap threw away --------
    n_drop = len(cands) - len(picked)
    log("NHC sample: kept %d of %d eligible storms (seed %d), dropped %d "
        "to the %d-storm cap" % (len(picked), len(cands), seed, n_drop,
                                 n_target))
    by_basin_kept = defaultdict(int)
    by_basin_all = defaultdict(int)
    for e, _ in picked:
        by_basin_kept[e["basin"]] += 1
    for e, _ in cands:
        by_basin_all[e["basin"]] += 1
    for basin in NHC_BASINS:
        log("    %s  kept %3d / %3d eligible  (dropped %3d)"
            % (basin, by_basin_kept[basin], by_basin_all[basin],
               by_basin_all[basin] - by_basin_kept[basin]))
    for tier in TIERS:
        avail = sum(1 for e, _ in cands if tier_of(e["peakVmax"]) == tier)
        log("    %-18s kept %3d / %3d eligible  (dropped %3d)"
            % (TIER_LABEL[tier], tier_count[tier], avail,
               avail - tier_count[tier]))
    per_season = defaultdict(int)
    for e, _ in picked:
        per_season[(e["basin"], e["season"])] += 1
    log("    per season kept (NA/EP): " + " ".join(
        "%d:%d/%d" % (s, per_season[("NA", s)], per_season[("EP", s)])
        for s in seasons))
    missing = [(b, s) for b in NHC_BASINS for s in seasons
               if s >= BASIN_MIN_SEASON[b] and per_season[(b, s)] == 0]
    if missing:
        log("    WARNING seasons with no storm kept: %s"
            % ", ".join("%s %d" % m for m in missing))
    else:
        log("    every season %d-%d represented in both NHC basins"
            % (seasons[0], seasons[-1]))
    return picked


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------
def write_gs(path, index, storms, findings, log):
    """Emit the Apps Script bundle. ARCHIVE_STORMS is keyed by SID so
    Code.gs's getArchiveStorm(sid) is a single lookup - never a call that
    ships every storm at once."""
    n_rec = sum(len(v) for v in storms.values())
    with open(path, "w") as f:
        f.write("/**\n")
        f.write(" * Best-track archive for the TCWind_JTWC web app.\n")
        f.write(" * GENERATED by tests/tcwind_jtwc/prep_besttrack_data.py"
                " - do not hand-edit.\n")
        f.write(" * The same data, pretty-printed, is in"
                " tests/tcwind_jtwc/data/.\n")
        f.write(" *\n")
        f.write(" * ARCHIVE_INDEX   %d storms, metadata only. Served by"
                " getArchiveIndex().\n" % len(index))
        f.write(" * ARCHIVE_STORMS  {sid: [record, ...]}, %d records total.\n"
                % n_rec)
        f.write(" *                 Served ONE storm at a time by"
                " getArchiveStorm(sid).\n")
        f.write(" * GTCM_FINDINGS   contents of data/gtcm_findings.json"
                " (verify_gtcm.py),\n")
        f.write(" *                 or null if that file did not exist when"
                " this ran.\n")
        f.write(" *                 Served by getFindings().\n")
        f.write(" *\n")
        for basin in ("WP", "NA", "EP"):
            rows = [e for e in index if e["basin"] == basin]
            if not rows:
                continue
            f.write(" * %s  %3d storms, %5d records, seasons %d-%d (%s)\n"
                    % (basin, len(rows), sum(e["n"] for e in rows),
                       min(e["season"] for e in rows),
                       max(e["season"] for e in rows),
                       BASIN_AGENCY[basin]))
        f.write(" */\n")
        f.write("var ARCHIVE_INDEX = ")
        json.dump(index, f, separators=(",", ":"))
        f.write(";\n\n")
        f.write("var ARCHIVE_STORMS = ")
        json.dump(storms, f, separators=(",", ":"))
        f.write(";\n\n")
        f.write("var GTCM_FINDINGS = ")
        json.dump(findings, f, separators=(",", ":"))
        f.write(";\n")
    log("wrote %s" % path)


def human(n):
    return "%.1f KB" % (n / 1024.0) if n < 1024 * 1024 \
        else "%.2f MB" % (n / 1048576.0)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--na", default=None, help="IBTrACS North Atlantic CSV")
    ap.add_argument("--ep", default=None, help="IBTrACS East Pacific CSV")
    ap.add_argument("--wp-sample", default=WP_SAMPLE,
                    help="existing WestPac 100-storm sample JSON (read-only)")
    ap.add_argument("--findings", default=FINDINGS_JSON,
                    help="gtcm_findings.json to bundle (owned by "
                         "verify_gtcm.py; null if absent)")
    ap.add_argument("--n-nhc", type=int, default=N_NHC_STORMS,
                    help="cap on NA+EP storms (default %d)" % N_NHC_STORMS)
    ap.add_argument("--seed", type=int, default=SEED)
    args = ap.parse_args()

    lines = []

    def log(msg):
        print(msg)
        lines.append(msg)

    paths = {"NA": args.na or cache_path("NA"),
             "EP": args.ep or cache_path("EP")}
    for basin, p in sorted(paths.items()):
        log("%s CSV: %s" % (basin, p))

    cands = load_nhc_candidates(paths, log)
    nhc = stratified_sample(cands, args.n_nhc, args.seed, log)

    wp = load_westpac(args.wp_sample)
    log("WP: %d storms, %d records reused from %s (read-only; the WP CSV is "
        "not available, so this is repackaged, not re-derived)"
        % (len(wp), sum(len(r) for _, r in wp), args.wp_sample))

    combined = wp + nhc
    index = [e for e, _ in combined]
    index.sort(key=lambda e: (e["basin"], e["season"], e["sid"]))
    storms = OrderedDict()
    for e, recs in sorted(combined, key=lambda er: (er[0]["basin"],
                                                    er[0]["season"],
                                                    er[0]["sid"])):
        storms[e["sid"]] = recs

    for e in index:
        if e["maxLon"] > 180.0:
            log("NOTE %s %s %s (%d) crosses the dateline; its index bbox is "
                "unwrapped, so maxLon=%.2f exceeds 180"
                % (e["basin"], e["sid"], e["name"], e["season"], e["maxLon"]))

    if len(storms) != len(index):
        raise SystemExit("duplicate SID across basins: %d index rows but %d "
                         "distinct sids" % (len(index), len(storms)))

    findings = None
    if os.path.exists(args.findings):
        with open(args.findings) as f:
            findings = json.load(f)
        log("bundled %s (%s) as GTCM_FINDINGS"
            % (args.findings, human(os.path.getsize(args.findings))))
    else:
        log("WARNING: %s does not exist yet - GTCM_FINDINGS will be null and "
            "Code.gs's getFindings() will return null. Run verify_gtcm.py, "
            "then re-run this script to bundle it." % args.findings)

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(INDEX_JSON, "w") as f:
        json.dump(index, f, indent=1)
    with open(STORMS_JSON, "w") as f:
        json.dump(storms, f, separators=(",", ":"))
    write_gs(GS_OUT, index, storms, findings, log)

    log("")
    log("ARCHIVE TOTAL: %d storms, %d records"
        % (len(index), sum(e["n"] for e in index)))
    for basin in ("WP", "NA", "EP"):
        rows = [e for e in index if e["basin"] == basin]
        log("  %s  %3d storms  %5d records  %5d with radii  seasons %d-%d"
            % (basin, len(rows), sum(e["n"] for e in rows),
               sum(e["radiiRecords"] for e in rows),
               min(e["season"] for e in rows), max(e["season"] for e in rows)))

    sizes = [(INDEX_JSON, INDEX_SOFT_LIMIT), (STORMS_JSON, None),
             (GS_OUT, GS_SOFT_LIMIT)]
    log("")
    for path, limit in sizes:
        n = os.path.getsize(path)
        flag = ""
        if limit and n > limit:
            flag = "  *** OVER the %s soft limit ***" % human(limit)
        log("  %-52s %10s%s" % (os.path.relpath(path, os.path.join(HERE,
                                                                   "..", "..")),
                                human(n), flag))
    return 0


if __name__ == "__main__":
    sys.exit(main())
